---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://127.0.0.1:9443/mutate-cni-tanzu-vmware-com-v1alpha1-antreaconfig"
  failurePolicy: Fail
  name: mantreaconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - antreaconfigs
  sideEffects: None
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://127.0.0.1:9443/mutate-cni-tanzu-vmware-com-v1alpha1-calicoconfig"
  failurePolicy: Fail
  name: mcalicoconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calicoconfigs
  sideEffects: None
  timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://127.0.0.1:9443/validate-cni-tanzu-vmware-com-v1alpha1-antreaconfig"
  failurePolicy: Fail
  name: vantreaconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - antreaconfigs
  sideEffects: None
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://127.0.0.1:9443/validate-cni-tanzu-vmware-com-v1alpha1-calicoconfig"
  failurePolicy: Fail
  name: vcalicoconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calicoconfigs
  sideEffects: None
  timeoutSeconds: 30
