---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREF4TVJBd0RnWURWUVFLRXdkVVpYTjAKVDNKbk1SMHdHd1lEVlFRREV4UnpaV3htTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qQXlNamd4TVRBMwpOVEZhRncwek1qQXlNall4TVRBM05URmFNREV4RURBT0JnTlZCQW9UQjFSbGMzUlBjbWN4SFRBYkJnTlZCQU1UCkZITmxiR1l0YzJsbmJtVmtMV3M0Y3kxalpYSjBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFzWDQ0OHlSckRGVjNpU0ZJS0hOelVPWEZlbW1BUkxaOGo5S2libXdlRHQyMjV1bVJ4WGR5a2dPMQpTWmNNb1J6MDNlbWQ5WXZ5d1F6VlZwRGRUWTA0eVhoVXRna1dLeURneUVybys1S3BuY1NQWWhSTFJ4SnVSSXphCklDSnVOMmxLS0ExZUJhZ3hBM05xdUhJMCtYZjlldjFTa1JRbjlCQXNibCtLamliRkZmRjh1SGdWdloxUVdhOFAKZW1vUGNXR1VOWWh4NFVrM255eERyVXpLYmxSUytjK244Y1BnQVBlTFBydkMwWFJoQWlybSsra2w5Z3FwN0k2NgpoQUw2MFprYkNaYTQrTHFpRXJTUml1MlpBOEljaUMrb29ZY2pnSWZMTkFGRDUybWlJSFdoeVc0Z2F5RFBocjlECm00dXV4MFNDcDI5TFh3anNwREh5eGxqeUZ0Qi9rd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTDRBWG1kaUNEcTQ1N0dkdGZOUFlMaSt5cHZzdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0FhcG80eHVCT1hkRktlbXBaRFpzSHBkdVpRODdpOFc3NzNpaEwyCmd4NDMxdzFudE5zaGwxOVc4RXFhQ3FMQkphRkRmSVZ5dTVGczl1TTJaSXVUaFYvN0ZaN1JCQlBRWWxmdlQrUG8KeGZRcHdVV0FxUEZsY21jL1hvVXFKNUR6V1Rkb2ROK1JJMnl5dEcrMmhZVnZabkZpeG1ONEJ2L3N5WHpzbVg3aAowcVhudEQrVUFOVHNtUzJsUUNCbEJpTTVSRjNVWitSR2tKQytsOUFUTEUzQWwrcXhLMktWcmlyOHBBSEwxQld3Ck83cnNkbnhqV0xMTGpsTWY0VzNOZUozM1dYVDFlaFZlYlRpTnlnODBPZS9GVU54a04rc0VjUUF5VTRBamZua0wKVVdiUENLNjU1c3dta0pyRVhZMnJUMEZvWFZKVThaZmVQTWpPVG4zRXU3RHFrYkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    url: "https://127.0.0.1:9443/mutate-cni-tanzu-vmware-com-v1alpha1-antreaconfig"
  failurePolicy: Fail
  name: mantreaconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - antreaconfigs
  sideEffects: None
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREF4TVJBd0RnWURWUVFLRXdkVVpYTjAKVDNKbk1SMHdHd1lEVlFRREV4UnpaV3htTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qQXlNamd4TVRBMwpOVEZhRncwek1qQXlNall4TVRBM05URmFNREV4RURBT0JnTlZCQW9UQjFSbGMzUlBjbWN4SFRBYkJnTlZCQU1UCkZITmxiR1l0YzJsbmJtVmtMV3M0Y3kxalpYSjBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFzWDQ0OHlSckRGVjNpU0ZJS0hOelVPWEZlbW1BUkxaOGo5S2libXdlRHQyMjV1bVJ4WGR5a2dPMQpTWmNNb1J6MDNlbWQ5WXZ5d1F6VlZwRGRUWTA0eVhoVXRna1dLeURneUVybys1S3BuY1NQWWhSTFJ4SnVSSXphCklDSnVOMmxLS0ExZUJhZ3hBM05xdUhJMCtYZjlldjFTa1JRbjlCQXNibCtLamliRkZmRjh1SGdWdloxUVdhOFAKZW1vUGNXR1VOWWh4NFVrM255eERyVXpLYmxSUytjK244Y1BnQVBlTFBydkMwWFJoQWlybSsra2w5Z3FwN0k2NgpoQUw2MFprYkNaYTQrTHFpRXJTUml1MlpBOEljaUMrb29ZY2pnSWZMTkFGRDUybWlJSFdoeVc0Z2F5RFBocjlECm00dXV4MFNDcDI5TFh3anNwREh5eGxqeUZ0Qi9rd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTDRBWG1kaUNEcTQ1N0dkdGZOUFlMaSt5cHZzdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0FhcG80eHVCT1hkRktlbXBaRFpzSHBkdVpRODdpOFc3NzNpaEwyCmd4NDMxdzFudE5zaGwxOVc4RXFhQ3FMQkphRkRmSVZ5dTVGczl1TTJaSXVUaFYvN0ZaN1JCQlBRWWxmdlQrUG8KeGZRcHdVV0FxUEZsY21jL1hvVXFKNUR6V1Rkb2ROK1JJMnl5dEcrMmhZVnZabkZpeG1ONEJ2L3N5WHpzbVg3aAowcVhudEQrVUFOVHNtUzJsUUNCbEJpTTVSRjNVWitSR2tKQytsOUFUTEUzQWwrcXhLMktWcmlyOHBBSEwxQld3Ck83cnNkbnhqV0xMTGpsTWY0VzNOZUozM1dYVDFlaFZlYlRpTnlnODBPZS9GVU54a04rc0VjUUF5VTRBamZua0wKVVdiUENLNjU1c3dta0pyRVhZMnJUMEZvWFZKVThaZmVQTWpPVG4zRXU3RHFrYkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    url: "https://127.0.0.1:9443/mutate-cni-tanzu-vmware-com-v1alpha1-calicoconfig"
  failurePolicy: Fail
  name: mcalicoconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calicoconfigs
  sideEffects: None
  timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREF4TVJBd0RnWURWUVFLRXdkVVpYTjAKVDNKbk1SMHdHd1lEVlFRREV4UnpaV3htTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qQXlNamd4TVRBMwpOVEZhRncwek1qQXlNall4TVRBM05URmFNREV4RURBT0JnTlZCQW9UQjFSbGMzUlBjbWN4SFRBYkJnTlZCQU1UCkZITmxiR1l0YzJsbmJtVmtMV3M0Y3kxalpYSjBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFzWDQ0OHlSckRGVjNpU0ZJS0hOelVPWEZlbW1BUkxaOGo5S2libXdlRHQyMjV1bVJ4WGR5a2dPMQpTWmNNb1J6MDNlbWQ5WXZ5d1F6VlZwRGRUWTA0eVhoVXRna1dLeURneUVybys1S3BuY1NQWWhSTFJ4SnVSSXphCklDSnVOMmxLS0ExZUJhZ3hBM05xdUhJMCtYZjlldjFTa1JRbjlCQXNibCtLamliRkZmRjh1SGdWdloxUVdhOFAKZW1vUGNXR1VOWWh4NFVrM255eERyVXpLYmxSUytjK244Y1BnQVBlTFBydkMwWFJoQWlybSsra2w5Z3FwN0k2NgpoQUw2MFprYkNaYTQrTHFpRXJTUml1MlpBOEljaUMrb29ZY2pnSWZMTkFGRDUybWlJSFdoeVc0Z2F5RFBocjlECm00dXV4MFNDcDI5TFh3anNwREh5eGxqeUZ0Qi9rd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTDRBWG1kaUNEcTQ1N0dkdGZOUFlMaSt5cHZzdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0FhcG80eHVCT1hkRktlbXBaRFpzSHBkdVpRODdpOFc3NzNpaEwyCmd4NDMxdzFudE5zaGwxOVc4RXFhQ3FMQkphRkRmSVZ5dTVGczl1TTJaSXVUaFYvN0ZaN1JCQlBRWWxmdlQrUG8KeGZRcHdVV0FxUEZsY21jL1hvVXFKNUR6V1Rkb2ROK1JJMnl5dEcrMmhZVnZabkZpeG1ONEJ2L3N5WHpzbVg3aAowcVhudEQrVUFOVHNtUzJsUUNCbEJpTTVSRjNVWitSR2tKQytsOUFUTEUzQWwrcXhLMktWcmlyOHBBSEwxQld3Ck83cnNkbnhqV0xMTGpsTWY0VzNOZUozM1dYVDFlaFZlYlRpTnlnODBPZS9GVU54a04rc0VjUUF5VTRBamZua0wKVVdiUENLNjU1c3dta0pyRVhZMnJUMEZvWFZKVThaZmVQTWpPVG4zRXU3RHFrYkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    url: "https://127.0.0.1:9443/validate-cni-tanzu-vmware-com-v1alpha1-antreaconfig"
  failurePolicy: Fail
  name: vantreaconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - antreaconfigs
  sideEffects: None
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREF4TVJBd0RnWURWUVFLRXdkVVpYTjAKVDNKbk1SMHdHd1lEVlFRREV4UnpaV3htTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qQXlNamd4TVRBMwpOVEZhRncwek1qQXlNall4TVRBM05URmFNREV4RURBT0JnTlZCQW9UQjFSbGMzUlBjbWN4SFRBYkJnTlZCQU1UCkZITmxiR1l0YzJsbmJtVmtMV3M0Y3kxalpYSjBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFzWDQ0OHlSckRGVjNpU0ZJS0hOelVPWEZlbW1BUkxaOGo5S2libXdlRHQyMjV1bVJ4WGR5a2dPMQpTWmNNb1J6MDNlbWQ5WXZ5d1F6VlZwRGRUWTA0eVhoVXRna1dLeURneUVybys1S3BuY1NQWWhSTFJ4SnVSSXphCklDSnVOMmxLS0ExZUJhZ3hBM05xdUhJMCtYZjlldjFTa1JRbjlCQXNibCtLamliRkZmRjh1SGdWdloxUVdhOFAKZW1vUGNXR1VOWWh4NFVrM255eERyVXpLYmxSUytjK244Y1BnQVBlTFBydkMwWFJoQWlybSsra2w5Z3FwN0k2NgpoQUw2MFprYkNaYTQrTHFpRXJTUml1MlpBOEljaUMrb29ZY2pnSWZMTkFGRDUybWlJSFdoeVc0Z2F5RFBocjlECm00dXV4MFNDcDI5TFh3anNwREh5eGxqeUZ0Qi9rd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTDRBWG1kaUNEcTQ1N0dkdGZOUFlMaSt5cHZzdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0FhcG80eHVCT1hkRktlbXBaRFpzSHBkdVpRODdpOFc3NzNpaEwyCmd4NDMxdzFudE5zaGwxOVc4RXFhQ3FMQkphRkRmSVZ5dTVGczl1TTJaSXVUaFYvN0ZaN1JCQlBRWWxmdlQrUG8KeGZRcHdVV0FxUEZsY21jL1hvVXFKNUR6V1Rkb2ROK1JJMnl5dEcrMmhZVnZabkZpeG1ONEJ2L3N5WHpzbVg3aAowcVhudEQrVUFOVHNtUzJsUUNCbEJpTTVSRjNVWitSR2tKQytsOUFUTEUzQWwrcXhLMktWcmlyOHBBSEwxQld3Ck83cnNkbnhqV0xMTGpsTWY0VzNOZUozM1dYVDFlaFZlYlRpTnlnODBPZS9GVU54a04rc0VjUUF5VTRBamZua0wKVVdiUENLNjU1c3dta0pyRVhZMnJUMEZvWFZKVThaZmVQTWpPVG4zRXU3RHFrYkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    url: "https://127.0.0.1:9443/validate-cni-tanzu-vmware-com-v1alpha1-calicoconfig"
  failurePolicy: Fail
  name: vcalicoconfig.kb.io
  rules:
  - apiGroups:
    - cni.tanzu.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calicoconfigs
  sideEffects: None
  timeoutSeconds: 30

